### ISSUE TITLE
團員資料增修申請區

### ISSUE THREAD

**Issue by fntsrlike** [ChildishGhost/ChildishGhost.github.io#2]
本Issue提供給不會使用Git相關工具的團員們使用，讓團員們能夠在這邊留下資料後，再由會使用的團員協助更新到頁面上。

關於頭像，若是有在使用Gravatar服務的，可以使用「 http://asaph.org/gravatar/ 」去產生頭像網址，若沒有，亦可將檔案放在 `images/member_avatar/`下，以自己的id命名，建議頭像圖檔大小不要太大，避免早成讀取太慢的問題。另外本頁面頭像是以正方形呈現，若是長寬不等長可能為產生變形的情況哦。

請欲申請的團員以下方格式回覆您的資料，若沒該項資料，請用兩個單引號作為留空，複製貼上後，請在文本上下方都附上「```」以保持排版：

```
  * id: '請填寫您的慣用ID（英文數字組成）'
    nick: '請填寫您的暱稱'
    title: '請填寫您的稱號，通常是團牌上面的稱號'
    identity: '請填寫您的身份'
    avatar: '您的個人頭像連結，建議使用正方形'
    content: '您的個人敘述'
    social:
      * github: 'github個人頁面網址'
        google: 'google個人頁面網址'
        facebook: 'facebook個人頁面網址'
        instagram: 'instagram個人頁面網址'
        twitter: ' twitter個人頁面網址'
        plurk: 'plurk個人頁面網址'

```

範例

```
  * id: 'david50407',
    nick: '喜德',
    title: '家貓',
    identity: '',
    avatar: 'http://i.imgur.com/w4eq46u.jpg',
    content: '喵~'
    social:
      * github: 'https://github.com/david50407''
        google: ''
        facebook: ''
        instagram: ''
        twitter: ''
        plurk: ''
```
